name: dart_webgl
author: Julien Castelain <jcastelain@gmail.com>
description: WebGL stuff with Dart.

environment:
  sdk: ">=0.8.10+6 <2.0.0"

dependencies:
  browser: any
  vector_math: ">=1.4.3 <2.0.0"
